image: gosignmedia/deploy

stages:
- test
- deploy

test:
  stage: test
  script:
    - php -l *.php

deploy to production:
  when: manual
  stage: deploy
  script: echo 'test'
  environment: production
